      - name: Determine changed report files
        id: changes
        run: |
          set -e
          git fetch --no-tags --depth=2 origin ${{ github.ref }}

          if [[ "${{ github.event_name }}" == "push" ]]; then
            BEFORE="${{ github.event.before }}"
            AFTER="${{ github.sha }}"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BEFORE="${{ github.event.pull_request.base.sha }}"
            AFTER="${{ github.event.pull_request.head.sha }}"
          else
            # workflow_dispatch / schedule — compare to previous commit if possible, else scan all
            BEFORE="$(git rev-parse HEAD~1 2>/dev/null || echo '')"
            AFTER="$(git rev-parse HEAD)"
          fi

          if [[ -n "$BEFORE" ]]; then
            DIFF_RANGE="$BEFORE..$AFTER"
            CHANGED=$(git diff --name-only "$DIFF_RANGE" -- '*.md' | tr '\n' ' ' || true)
          else
            # Fallback: no BEFORE available — just scan all markdown files
            CHANGED=$(git ls-files '*.md' | tr '\n' ' ' || true)
          fi

          echo "changed=$CHANGED" >> $GITHUB_OUTPUT
